vnexpress:
  disaster_categories:
    - https://vnexpress.net/thoi-su
    - https://vnexpress.net/dan-sinh
    - https://vnexpress.net/giao-thong
    - https://vnexpress.net/khoa-hoc/the-gioi-tu-nhien
    - https://vnexpress.net/goc-nhin/moi-truong